### ISSUE TITLE
japanese preprocessed files and jp_labels.json

### ISSUE THREAD

**Issue by aguang1201** [JeanMaximilienCadic/ASRDeepSpeech#2]
Hello, I sent you an email for jp_labels.json, but I didn't get a reply. So here to consult you, can you provide the japanese preprocessed files and jp_labels.json?I want to train Japanese ASR model, these files are very helpful for my work, thank you very much.

**Comment by JeanMaximilienCadic** [comment]
Hi,

Sorry for my late reply. you can find the labels here. https://github.com/JeanMaximilienCadic/ASRDeepSpeech/tree/docker/__data__/labels

I am refactoring the code to add a support for docker, I will push the code during this month.

Jean
