### ISSUE TITLE
Pretrained Japanese language model 

### ISSUE THREAD

**Issue by marlon-br** [JeanMaximilienCadic/ASRDeepSpeech#3]
Hi, is there any pretrained model for Japanese language available? I would like to try how it works

Thanks in advance

**Comment by JeanMaximilienCadic** [comment]
Hi marlon-br,

Sorry for my late reply I am working on that, I will push the model during this month.

Jean

**Comment by ck196** [comment]
@JeanMaximilienCadic Are you working on it?

**Comment by JeanMaximilienCadic** [comment]
Yes but essentially it takes time to train so please wait again a bit.

Jean

**Comment by JeanMaximilienCadic** [comment]
I have pushed a pretrained model on the master branch. Please check it !
